### ISSUE TITLE
Vult Modules don't work in VCVRack .32

### ISSUE THREAD

**Issue by killiun** [modlfo/VultModules#1]
Love these but they don't seem to work in the new version.

**Comment by modlfo** [comment]
Thank you for letting me know. I have recompiled the modules for version 0.3.2. They are available in the releases page.

**Comment by antoniograzioli** [comment]
On mac I was able to compile them in 0.3.2

**Comment by antoniotuzzi** [comment]
![screen shot 2017-09-27 at 15 48 21](https://user-images.githubusercontent.com/62518/30917077-5bb5a012-a39b-11e7-837b-22f38d9580b6.png)
in menu too

**Comment by modlfo** [comment]
Thank  you for testing them. The recompiled modules (https://github.com/modlfo/VultModules/releases/tag/VCVRack-v0.3.2) work for me in Linux, Mac and Windows for Rack version 0.3.2. I'm gonna close this one but let me know in case the plugins do not work for you in any of the platforms.
