### ISSUE TITLE
steiner-parker filter hiss

### ISSUE THREAD

**Issue by emhere** [modlfo/VultModules#10]
not sure if this is easily fixable but here's an example:

https://soundcloud.com/unslept_em/vcv-patch-1

thanks for your work, been really enjoying the modules

**Comment by modlfo** [comment]
I think is because of the noise I have to insert in order to self modulate. I will fix it so the noise is inserted only when nothing is connected.

**Comment by modlfo** [comment]
I have released a new version. Can you check if you still have hiss?

**Comment by emhere** [comment]
no hiss!
