### ISSUE TITLE
Util-Bypass > Control state not retained on save being reloaded

### ISSUE THREAD

**Issue by patman023** [modlfo/VultModules#18]
as per title. Module always bypassed on reload.

[apr30-2-b.zip](https://github.com/modlfo/VultModules/files/1974701/apr30-2-b.zip)

**Comment by modlfo** [comment]
Thank you for the report. I was not aware it was not working. I will fix it in the next release.

**Comment by modlfo** [comment]
I fixed this one a while ago but I haven't released an update. It should work in versions v0.6.4
