### ISSUE TITLE
Upgrade causes modules to not work anymore on Debian 9

### ISSUE THREAD

**Issue by WouterSpekkink** [modlfo/VultModules#20]
Hi, thanks for your great modules. I am using your commercial package. After your most recent update, the Vult modules no longer load on my system (Debian 9). The log reports that my system is missing GLIBC_2.27 (see the entry below).

[0.191 warn src/plugin.cpp:90] Failed to load library /home/wouter/.Rack/plugins/VultModules/plugin.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/wouter/.Rack/plugins/VultModules/plugin.so)

After some googling I found out that the issue is that Debian 9 uses libc 2.24, whereas Vult depends on libc 2.27. I tried to download the latest libc library from the Debian unstable repository, but I had to abort that because it required me to make a lot of significant changes to my Debian installation. 

Would it be possible for you to build the modules with a downgraded version of the libc library? I am also happy to build myself.

**Comment by modlfo** [comment]
I'll release very soon a new version of all the linux binaries compiled with ubuntu 16.04 which seems to use an older libc. This was the ubuntu version I used to compile the modules before.

**Comment by WouterSpekkink** [comment]
That is great news! Thanks.

**Comment by WouterSpekkink** [comment]
I had already closed the issue, but just wanted to confirm that everything works again now. Thanks for your quick action. I like the new look!
