### ISSUE TITLE
Legacy Vult versions?

### ISSUE THREAD

**Issue by danpetry** [modlfo/VultModules#21]
Hi there
I just upgraded VCV rack (including my modules) and due to rendering problems in Ubuntu, I need to roll back. I've got a lot of patches using Vult modules which I would really like to not use. I have vult-free but can only get it for the latest version of vcv Rack (ie. 0.6). Is there any way I can get a build for Rack v0.5.1?

**Comment by modlfo** [comment]
Sadly I don't keep an archive of releases. I'll have to setup from scratch a new build of Rack v0.5 and my modules.

Ask in the facebook group if someone has archived the free modules for v.0.5.

**Comment by danpetry** [comment]
Hi @modlfo , thanks for the support. I ended up sorting out the rendering problems and keeping the upgrade. Thanks for the quick reply and the good work.
