### ISSUE TITLE
Bypass blocks signal initially

### ISSUE THREAD

**Issue by jonheal** [modlfo/VultModules#22]
Leonardo,

I notice with Bypass hooked up in the signal path, it initially blocks the signal (at least when cables are hooked up to the Send and Return jacks). I have to press the Control button once to get the signal to pass. Is this by design?

**Comment by modlfo** [comment]
My idea was that when you add a bypass module, the input goes straight to the output. When pressing the button, the input goes into the send/return effect. This was to imitate how most of the guitar pedal I have work. When powered, the effect is off, and until you press the button you hear the effect.

**Comment by jonheal** [comment]
OK.

--
Jon Heal
http://www.theheals.org/
Have a nice day!
