### ISSUE TITLE
Can't download Free modules

### ISSUE THREAD

**Issue by shougan** [modlfo/VultModules#23]
Hi, I'd like to download free modules, but there is only readme and license files in the release archives. How can I download them?( I'm building vcv rack and modules from source, so just add plugin on vcv account plugins page does not work for me  )

**Comment by modlfo** [comment]
The only way of getting them is through VCV. If you are building it by yourself run Rack with `$make runr`. That launches Rack in release mode and you can login to your account and download all the plugins you have on it.

**Comment by modlfo** [comment]
If that does not work for you. Send me an email telling me for which platform you want the modules and I'll send you a link. However, the best way of staying up-to-date is by getting the updates with VCV Rack.

**Comment by modlfo** [comment]
I have sent you a link to download it. Other alternative is that you can install the official VCV Rack executable and you can launch your own build pointing it to load the plugins from the Documents/Rack/plugins folder. I know there's a flag for that but I don't remember it.

**Comment by shougan** [comment]
Thanks! "Documents/Rack/plugins folder." I did not know about this.
