### ISSUE TITLE
3 HP Blank Plate is not blank

### ISSUE THREAD

**Issue by mikeloveridge** [modlfo/VultModules#25]
Hi, I just noticed the 3 HP blank looks like a module and I don't know if it's intentional or not.  If this is intentional, then please ignore this issue.  This is true for both Vult and Vult Free.

Mike

**Comment by modlfo** [comment]
Yes, I added some functionality to the blank. It produces the Vult (and Omri Cohen's) logo through the x,y outputs when connected to the scope. In the image below is not possible to see it all, but that's the idea.

<img width="291" alt="logo" src="https://user-images.githubusercontent.com/2001046/47898058-e4c18980-de7c-11e8-8112-944a72c98485.png">
