### ISSUE TITLE
Intermittent: Bypass doesn't output on patch load

### ISSUE THREAD

**Issue by patman023** [modlfo/VultModules#26]
Intermittent: either on loading as autosave or from file, Bypass doesn't output on patch load

control must be activated before it will pass through.

Both Vult Free and Vult Premium (both 0.6.20)

Rack 0.6.2b
Win10

[bypass.txt](https://github.com/modlfo/VultModules/files/2719769/bypass.txt)

**Comment by modlfo** [comment]
I found the error. It will be fixed in the next release. Bypass and Send are the only modules that are not written in Vult language and seem to be the ones that have had more bugs :)

**Comment by patman023** [comment]
Gotcha. Go figure that something relatively simple would be so full of problems :-P
