### ISSUE TITLE
Noxious - poly "Out" has no signal out with "level" all the way down.

### ISSUE THREAD

**Issue by dkincaid** [modlfo/VultModules#29]
In Noxious poly the "Out" jacks for the poly signals isn't outputting anything with the level knob all the way to the left. If I turn up the level knob the signal starts coming out. However, the manual says that the level knob isn't supposed to affect the individual poly output signals.

**Comment by modlfo** [comment]
This looks like a bug I introduced in one of the recent updates. Thanks for the report. I'll fix it in the next release.

**Comment by modlfo** [comment]
This should be fixed in v0.6.26 of the modules.
