### ISSUE TITLE
Missing "model" switch on Lateralus

### ISSUE THREAD

**Issue by jimmckerchar** [modlfo/VultModules#30]
![lateralus missing switch fw](https://user-images.githubusercontent.com/160853/53795277-88a16b80-3f29-11e9-8c34-e8ccbebd6032.png)

It hasn't stopped my enjoyment of the module (i actually only just noticed) but I seem to be missing a switch on the Lateralus filter.

**Comment by patman023** [comment]
If you only have Vult Free, then you won't have a model switch.

**Comment by patman023** [comment]
![](https://modlfo.github.io/VultModules/images/VultFamily.png)

**Comment by jimmckerchar** [comment]
ah thanks that  makes sense :D
