### ISSUE TITLE
Caudal stops and send mutes

### ISSUE THREAD

**Issue by Petervos2018** [modlfo/VultModules#31]
Hi Leonardo, 

[Caudal-Send-Bug-10032019.zip](https://github.com/modlfo/VultModules/files/2949789/Caudal-Send-Bug-10032019.zip)
Could you try this project I have attached and see if you got the same results ?
Please load the project, change the audio settings to what you normally use in the core module.
Close rack, open rack.
If all went right/wrong you will hear nothing, this is because send is muting the sounds.
Wiggle the knob to get it going.
Also Caudal is not changing any of its outputs, sometimes you have to wait a while but it **will stop**.
Please open/close rack a few times before you tell me none of the above is happening on your set-up, and you can't reproduce this.

Greetings Peter.

**Comment by modlfo** [comment]
I checked both issues.

The problem with Send is in fact a bug and I will release a fix soon in the next release.

The problem with Caudal is that you are using one of it's outputs to modulate the Speed. Since the outputs are bipolar, when Caudal sends a negative signal (like -5V) it makes the speed go down. If you want to self-modulate Caudal, you can use something like Leakage to add an offset and make the signal positive so it does not slow down.

**Comment by Petervos2018** [comment]
> The problem with Caudal is that you are using one of it's outputs to modulate the Speed.

I somehow knew that you were going to say that, so I did some testing, and this "Bug" was introduced with version 6.022, the time you changed the solver.
Versions 6.021 and older do not behave like this !
They may slow down.... but they do not stop completely/come to a grinding halt.
I think there is a bug in your new solver.

> you can use something like Leakage to add an offset and make the signal positive so it does not slow down.

Like this ? :
[VultTest-11032019 V621OK.zip](https://github.com/modlfo/VultModules/files/2952553/VultTest-11032019.V621OK.zip)

This also comes to a halt!

Thanks for checking it all out and I really love your modules, also good luck with your beautiful hardware.

Greetings Peter.

**Comment by modlfo** [comment]
Thanks for taking the time. With the new solver of Caudal I also implemented a feature to reduce the numbers of simulation step calculated. Seems like that feature is not playing well with modulating the speed. I'll try to make it work better in the next release.

**Comment by modlfo** [comment]
I have fixed these two issues in v0.6.26.
