### ISSUE TITLE
Bug: Julste - Switch from VCA to Lowpass pops nastily

### ISSUE THREAD

**Issue by patman023** [modlfo/VultModules#32]

**Comment by patman023** [comment]
[julste pop.txt](https://github.com/modlfo/VultModules/files/2984808/julste.pop.txt)

**Comment by modlfo** [comment]
I usually don't do anything to avoid the pops when moving the switches because trying to remove the pops requires spending CPU detecting and softening the transitions. 

The only switches that have softening of transitions are the ones that are meant to be modulated.

**Comment by patman023** [comment]
Ah. Fair enough. I'll rig up a sequential switch then. 😊
