### ISSUE TITLE
Vessek tuned 3 octaves down.

### ISSUE THREAD

**Issue by demourne** [modlfo/VultModules#33]
I tried out Vessek. But at my computer it is tuned down 3 octaves. 
In the patch it can be tested. 
Does anybody know a solution?
Or am I the problem?

[issue_test.zip](https://github.com/modlfo/VultModules/files/2991679/issue_test.zip)

**Comment by modlfo** [comment]
Now I understand what you mean. Vessek and all Vult oscillators do not use the same base tuning as the oscillators in VCV Rack. There's no written standard specifying what's the corresponding frequency for a given voltage, the only requirement that needs to be fulfilled is that an increment of 1V corresponds to one octave.

Modules like the one you used to provide the pitch signal assume that all modules have the same base pitch. If you want to have the same pitch as the others, use the Octave control to adjust to the octave the other oscillators use.

It's not an error per ser and changing that behaviour will break backwards compatibility with old patches.
