### ISSUE TITLE
Trummor mod source display text order

### ISSUE THREAD

**Issue by Coirt** [modlfo/VultModules#35]
The order of the text, on Trummor1' Noise mod source does not correspond with the order of the knobs on the noise side "Speed, Source,  Level" should be "Level, Source, Speed" to correspond with the order of the knobs from left to right.

It has not been changed since it was rearranged.

**Comment by modlfo** [comment]
Thanks for the report. I have fixed the order of the labels in the latests version of the binaries (the pre-release).

I noticed that one the "Decay" label is wrong in Trummor. I'll fix it in the next version.

**Comment by Coirt** [comment]
No problem, Yes that is true noticed that myself, it says "release" same difference...
