### ISSUE TITLE
Trummor2 sub knob tune

### ISSUE THREAD

**Issue by Coirt** [modlfo/VultModules#37]
Question for you what is frequency of the sub knob on trummor2?

It just doesn't sound right to me so I never use it, I would say it sounds out of tune.

**Comment by modlfo** [comment]
It's exactly one octave down. In retrospective, it would have been more useful to have it an octave up. It works better if you tune the drum up and then add the sub oscillator.

**Comment by modlfo** [comment]
Now Trummor 2 has asecond oscillator one octave up.
