### ISSUE TITLE
Noxious - CV modulation adds strange artifacts

### ISSUE THREAD

**Issue by espenstoro** [modlfo/VultModules#38]
Hi. Was messing around with Noxious. Rack 1.1.1 on Windows, plugin version 1.0.2. I believe there's a little bug here.

How to reproduce: Connect CV input from, say, Caudal, select any of the phase parameters, and a squealing nasty overtone appears when you turn up the CV levels, one that isn't there when you turn the knobs. Happens at different sample rates, which affects the pitch of the squeal.
Tested modulation via the µmap module, the problem goes away. Something related to the CV inputs?

Cheers,
ES

**Comment by modlfo** [comment]
Thanks Espen! I have fixed the problem and I'll release a fix soon.
