### ISSUE TITLE
SPLIE - not polyphonic on the bottom half

### ISSUE THREAD

**Issue by wapiflapi** [modlfo/VultModules#39]
I noticed SPLIE's top half works fine with polyphony but the bottom half doesn't.

Since the module is tagged polyphonic I'm assuming this is a bug and I hope this is the right place to report it. I don't know of any other polyphonic multiples so I was really hoping to use both halfs of this module.

Thanks for all the awesome work on the Vult modules!

**Comment by modlfo** [comment]
Thanks for the report! It's a bug. It will be fixed in the next release.
