### ISSUE TITLE
caudal polyphonic - all zero after first

### ISSUE THREAD

**Issue by glocke01** [modlfo/VultModules#43]
![caudal_poly_bug](https://user-images.githubusercontent.com/12255580/67297776-5e9cb980-f4b8-11e9-9fd7-1ce860f1afe8.png)

Caudal doesn't seem to be working in polyphonic mode. It outputs polyphonic cables, but all the outputs on the higher channels are zero. IIRC it used to work properly, so probably something small has broken.

Thanks for all the amazing modules.

**Comment by modlfo** [comment]
Thanks for the report! It's in fact a bug. It will be fixed in the next release.
