### ISSUE TITLE
drive on Freak mostly linear

### ISSUE THREAD

**Issue by glocke01** [modlfo/VultModules#45]
The drive control on Freak is acting very differently than the original models, with very little overdrive occurring. Playing around a little it seems to have a dynamic range just less than half of the original, at least with Tangents.
![freak_bug](https://user-images.githubusercontent.com/12255580/67509362-d1e12f80-f660-11e9-8dcf-4df95c5f4590.png)
the X-Y at right is VCO-1 (x) vs. Freak (y)

**Comment by modlfo** [comment]
Ohh, the Drive in Freak is limited. I inadvertently changed it. I will fix it in the next release. Let's hope it does not affect too much the patches.
