### ISSUE TITLE
TB-303 style filter

### ISSUE THREAD

**Issue by obust** [modlfo/VultModules#47]
I'd like to know which of the Freak filters can get the closest to 303 acid juicyness.

I read that the Roland TB-303 filter is a 18dB/oct diode ladder filter.
Would that mean that Lateralus in 18db mode can imitate it ?

**Comment by modlfo** [comment]
I have had the 303 filter in my list for a while, but I didn't had the time to make a prototype (hardware). I started building one. Hopefully it will work fine and I'll be able of modelling it.

**Comment by modlfo** [comment]
I have released Nitrous.

**Comment by obust** [comment]
could it be added to Freak ?

**Comment by modlfo** [comment]
It will be released in the next update
