### ISSUE TITLE
Sustain doesn't go to max when speed is set to hard on Slap

### ISSUE THREAD

**Issue by smerkley** [modlfo/VultModules#53]
Sustain functions normally when envelope is in "soft" but when set to "hard" the sustain only goes up to 3.6v

![image](https://user-images.githubusercontent.com/9426022/116018567-26b78a80-a5f7-11eb-81e5-13bf3e6ec4ec.png)

**Comment by modlfo** [comment]
thanks for the report! I check it out and fix it for the next release.

**Comment by modlfo** [comment]
I fixed this in the last release.
