### ISSUE TITLE
Freak odd polyphonic behaviour

### ISSUE THREAD

**Issue by paulpiko** [modlfo/VultModules#54]
I put the same VCO output into two polyphonic channels and send it to Freak. Then check the output of the two channels and they are unexpectedly very different.

![image](https://user-images.githubusercontent.com/56526215/134798112-c3677f52-493d-40f6-a4fc-9a75be42e61c.png)

**Comment by modlfo** [comment]
Hi @paulpiko 

can you consistently reproduce it? I have not been able of reproducing that behavior. Can you send me the patch?

**Comment by paulpiko** [comment]
Sorry Leonardo, I should have checked that. I restarted Rack and it's now working properly. Thanks for replying so quickly. I apologise for wasting your time.

**Comment by modlfo** [comment]
No problem. I don't have any idea how it happened.
