### ISSUE TITLE
v2 knobs sometimes do not fully turn

### ISSUE THREAD

**Issue by flyingLowSounds** [modlfo/VultModules#55]
in many instances when turning knobs, if I acheive an extreme value (e.g., 0 or 1) the knob itself stops short of the full cw or ccw position even though the tooltip reads 0 or 1. then, when turning in the other direction, the knob first snaps to the extreme full cw or ccw position before moving in the new direction.

**Comment by B0073D** [comment]
Can confirm I am also seeing this. (tested on Wolv)

**Comment by modlfo** [comment]
Thanks for the report. I have fixed the issue. I have updated the binaries in https://github.com/modlfo/VultModules/releases/tag/v2.0.0-042a9ce0
