### ISSUE TITLE
Trummor2 crashes rack v2 when opening any factory presets

### ISSUE THREAD

**Issue by ShofB** [modlfo/VultModules#56]
Title says it all.  I am running latest rack v2 on W10 with all latest updates.  It does not load any factory presets however user presets are fine.

**Comment by modlfo** [comment]
II think it has to do with the fact that the presets are created on the Premium version of Trummor 2. When trying to open a preset on the free version Rack crashes. I need to create the two versions of the presets and distribute them accordingly.

**Comment by modlfo** [comment]
This should be fixed in recent versions of the modules.
