### ISSUE TITLE
Opulus not visible in Rack

### ISSUE THREAD

**Issue by nay-seven** [modlfo/VultModules#57]
Hello,

just added the 2.0.5 , the presets and svg are visible in the dir, but modules don't appear in the browser ?
Rack Pro 2.0.6 MacOs Mojave

Thanks

**Comment by modlfo** [comment]
Can you send me the log.txt file to check if there are any issues there.

**Comment by nay-seven** [comment]
of course, here it is
[log.txt](https://github.com/modlfo/VultModules/files/8601008/log.txt)

**Comment by B0073D** [comment]
Not seeing this issue on Windows 10 2.0.6 VCV. Latest downloaded from library and am able to see new modules including Opulus.

**Comment by nay-seven** [comment]
ok, so my first test was from the release here in Github (https://github.com/modlfo/VultModules/releases/tag/v2.0.5)
Now i see the official update in Rack, click on "add " in the website  library, and it's ok now 
Thanks !
