### ISSUE TITLE
compilation with 0.4 fails

### ISSUE THREAD

**Issue by av500** [modlfo/VultModules#6]
this is needed:

```
--- a/src/VultModules.cpp
+++ b/src/VultModules.cpp
@@ -3,7 +3,7 @@
 
 float getSampleRate()
 {
-   return gSampleRate;
+   return engineGetSampleRate();
 }
 
 Plugin *plugin;
```

**Comment by modlfo** [comment]
Right now I'm compiling agains the tag v0.4 of Rack (latest release) and it works. That change is needed for compiling on master. Once the modules are stable I'm going to move to the master branch of Rack.

**Comment by av500** [comment]
ah ok. sorry for the noise then :)

**Comment by modlfo** [comment]
No problem. Thanks  for letting me know the fix!
