### ISSUE TITLE
Arm64 build of commercial VULT plugins?

### ISSUE THREAD

**Issue by fractalgee** [modlfo/VultModules#63]
Hi Leonardo, when can we get an arm64 Apple silicon native version of your plugins (commercial). I see a free version on releases for 2.0.8, but would like the commercial ones, as, for example, I can't miss the tangents XX mode ;)  Almost all there to run arm64 build of Rack as primary, but yours still sorely miss (as are very few others I consider essential to switch over for the most part)

**Comment by modlfo** [comment]
I'm in the process of preparing the binaries. I will send them to VCV as soon as I have them.

**Comment by fractalgee** [comment]
excellent, that makes 95% of what i need. The rest I can work around for now. Thanks a bunch.
