### ISSUE TITLE
Stabile CV INPUTS

### ISSUE THREAD

**Issue by djhyperspace** [modlfo/VultModules#7]
not sure if this in intentional.... the cv inputs for cutoff and res are not set to zero. when I right click it stays positive. I preferred it at zero to begin with so I can stop modulation and add just the right amount from zero. amazing work by the way. trummer is sickkkkkkkk

**Comment by modlfo** [comment]
I was not aware of that. I will check all my modules and make a new release.

**Comment by modlfo** [comment]
I have fixed the problem and the release is ready.

**Comment by djhyperspace** [comment]
mad skilllzzz
