### ISSUE TITLE
gsamplerate compilation error in Linux

### ISSUE THREAD

**Issue by Malifick** [modlfo/VultModules#8]
src/VultModules.cpp: In function ‘float getSampleRate()’:
src/VultModules.cpp:19:11: error: ‘gSampleRate’ was not declared in this scope
    return gSampleRate;
           ^~~~~~~~~~~
src/VultModules.cpp:19:11: note: suggested alternative: ‘getSampleRate’
    return gSampleRate;
           ^~~~~~~~~~~

**Comment by modlfo** [comment]
This is the same problem as #6 The Vult modules compile against the tag/v0.4.0 which is the last release. You can apply the fix shown in #6 to compile for a newer version.

**Comment by Malifick** [comment]
Ah thanks

**Comment by Malifick** [comment]
Ah..  one question , where do I put this code into ?

**Comment by modlfo** [comment]
VultModules.cpp line 17

https://github.com/modlfo/VultModules/blob/master/src/VultModules.cpp#L17

**Comment by Malifick** [comment]
Many thanks

**Comment by Malifick** [comment]
getting error now 
src/VultModules.cpp:34:1: error: stray ‘@’ in program
 @@ -3,7 +3,7 @@
 ^
src/VultModules.cpp:34:2: error: stray ‘@’ in program
 @@ -3,7 +3,7 @@
  ^
src/VultModules.cpp:34:14: error: stray ‘@’ in program
 @@ -3,7 +3,7 @@
              ^
src/VultModules.cpp:34:15: error: stray ‘@’ in program
 @@ -3,7 +3,7 @@
               ^
src/VultModules.cpp:32:1: error: expected unqualified-id before ‘--’ token
 --- a/src/VultModules.cpp
 ^~
src/VultModules.cpp: In function ‘float getSampleRate()’:
src/VultModules.cpp:45:11: error: ‘gSampleRate’ was not declared in this scope
    return gSampleRate;
           ^~~~~~~~~~~
src/VultModules.cpp:45:11: note: suggested alternative: ‘getSampleRate’
    return gSampleRate;
           ^~~~~~~~~~~
           getSampleRate
src/VultModules.cpp: At global scope:
src/VultModules.cpp:48:9: error: redefinition of ‘rack::Plugin* plugin’
 Plugin *plugin;
         ^~~~~~
src/VultModules.cpp:42:10: note: ‘rack::Plugin* plugin’ previously declared here
  Plugin *plugin;
          ^~~~~~
make: *** [../../compile.mk:55: build/src/VultModules.cpp.o] Error 1

**Comment by modlfo** [comment]
Later I will try to update the code to a newer version of Rack. Maybe the API has changed even more.

**Comment by modlfo** [comment]
After pull request #9 this builds against master
